language: python
dist: xenial # required for Python >= 3.7
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly" # nightly build
install:
  - pip install requests
script:
  - pytest
