language: python
dist: xenial # required for Python >= 3.7
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly" # nightly build
install:
  - pip install requests AttributeRouter pytest-cov pytest
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - pytest --cov
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
